% startup.m

% Set default values of several properties for the graphic object with
% handle 0, which is the root ancestor and default behavior for all plots.
% PropertyName is formed by concatenating the string 'Default', the object
% type (e.g., 'Figure', 'Axes', 'Line', and 'Text'), and the property name
% (e.g., 'Color', 'FontName', 'LineWidth').
%
% See also STARTUP SET

set(0, 'DefaultFigureColor', 'white', ...
'DefaultAxesColor', 'none', ...
'DefaultAxesFontAngle', 'normal', ...
'DefaultAxesFontName', 'Helvetica', ...
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontSize', 22, ...
'DefaultAxesFontWeight', 'normal', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesLineWidth', 2, ...
'DefaultAxesTickLength', [0.02,0.02], ...
'DefaultAxesUnits', 'inches', ...
'DefaultAxesPosition',[0.9 1.2 3.25 4],...
'DefaultAxesVisible', 'on', ...
'DefaultAxesXcolor', 'black', ...
'DefaultAxesYcolor', 'black', ...
'DefaultAxesZcolor', 'black', ...
'DefaultLineColor', 'black', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 2, ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 8, ...
'DefaultTextColor', 'black', ...
'DefaultTextFontName', 'Helvetica', ...
'DefaultTextFontUnits', 'points', ...
'DefaultTextFontSize', 24, ...
'DefaultTextFontWeight', 'normal', 'DefaultTextInterpreter','tex', ...
'DefaultTextHorizontalAlignment', 'left', ...
'DefaultTextVerticalAlignment', 'middle');
